package oracle.retail.apps.aipdt.xdos.model.view;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 21 16:23:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XDOrderScheduleTimeSetAllVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Dowseq {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getDowseq();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setDowseq((Integer) value);
            }
        }
        ,
        Sunday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getSunday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setSunday((Integer) value);
            }
        }
        ,
        Monday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getMonday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setMonday((Integer) value);
            }
        }
        ,
        Tuesday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getTuesday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setTuesday((Integer) value);
            }
        }
        ,
        Wednesday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getWednesday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setWednesday((Integer) value);
            }
        }
        ,
        Thursday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getThursday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setThursday((Integer) value);
            }
        }
        ,
        Friday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getFriday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setFriday((Integer) value);
            }
        }
        ,
        Saturday {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getSaturday();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setSaturday((Integer) value);
            }
        }
        ,
        Id {
            public Object get(XDOrderScheduleTimeSetAllVORowImpl obj) {
                return obj.getId();
            }

            public void put(XDOrderScheduleTimeSetAllVORowImpl obj, Object value) {
                obj.setId((BigDecimal) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XDOrderScheduleTimeSetAllVORowImpl object);

        public abstract void put(XDOrderScheduleTimeSetAllVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DOWSEQ = AttributesEnum.Dowseq.index();
    public static final int SUNDAY = AttributesEnum.Sunday.index();
    public static final int MONDAY = AttributesEnum.Monday.index();
    public static final int TUESDAY = AttributesEnum.Tuesday.index();
    public static final int WEDNESDAY = AttributesEnum.Wednesday.index();
    public static final int THURSDAY = AttributesEnum.Thursday.index();
    public static final int FRIDAY = AttributesEnum.Friday.index();
    public static final int SATURDAY = AttributesEnum.Saturday.index();
    public static final int ID = AttributesEnum.Id.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XDOrderScheduleTimeSetAllVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dowseq.
     * @return the Dowseq
     */
    public Integer getDowseq() {
        return (Integer) getAttributeInternal(DOWSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dowseq.
     * @param value value to set the  Dowseq
     */
    public void setDowseq(Integer value) {
        setAttributeInternal(DOWSEQ, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Sunday.
     * @return the Sunday
     */
    public Integer getSunday() {
        return (Integer) getAttributeInternal(SUNDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Sunday.
     * @param value value to set the  Sunday
     */
    public void setSunday(Integer value) {
        setAttributeInternal(SUNDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Monday.
     * @return the Monday
     */
    public Integer getMonday() {
        return (Integer) getAttributeInternal(MONDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Monday.
     * @param value value to set the  Monday
     */
    public void setMonday(Integer value) {
        setAttributeInternal(MONDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Tuesday.
     * @return the Tuesday
     */
    public Integer getTuesday() {
        return (Integer) getAttributeInternal(TUESDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Tuesday.
     * @param value value to set the  Tuesday
     */
    public void setTuesday(Integer value) {
        setAttributeInternal(TUESDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wednesday.
     * @return the Wednesday
     */
    public Integer getWednesday() {
        return (Integer) getAttributeInternal(WEDNESDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wednesday.
     * @param value value to set the  Wednesday
     */
    public void setWednesday(Integer value) {
        setAttributeInternal(WEDNESDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Thursday.
     * @return the Thursday
     */
    public Integer getThursday() {
        return (Integer) getAttributeInternal(THURSDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Thursday.
     * @param value value to set the  Thursday
     */
    public void setThursday(Integer value) {
        setAttributeInternal(THURSDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Friday.
     * @return the Friday
     */
    public Integer getFriday() {
        return (Integer) getAttributeInternal(FRIDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Friday.
     * @param value value to set the  Friday
     */
    public void setFriday(Integer value) {
        setAttributeInternal(FRIDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Saturday.
     * @return the Saturday
     */
    public Integer getSaturday() {
        return (Integer) getAttributeInternal(SATURDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Saturday.
     * @param value value to set the  Saturday
     */
    public void setSaturday(Integer value) {
        setAttributeInternal(SATURDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

