package oracle.retail.apps.aipdt.xdos.model.view;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 16 14:12:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XDOrderScheduleSearchVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Supplier {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSupplier();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setSupplier((String) value);
            }
        }
        ,
        SupplierList {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSupplierList();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setSupplierList((String) value);
            }
        }
        ,
        Department {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getDepartment();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setDepartment((String) value);
            }
        }
        ,
        Class1 {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getClass1();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setClass1((String) value);
            }
        }
        ,
        Subclass {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSubclass();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setSubclass((String) value);
            }
        }
        ,
        Vpn {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getVpn();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setVpn((String) value);
            }
        }
        ,
        StyleColor {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStyleColor();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setStyleColor((String) value);
            }
        }
        ,
        Item {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getItem();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setItem((String) value);
            }
        }
        ,
        ItemList {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getItemList();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setItemList((String) value);
            }
        }
        ,
        Region {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getRegion();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setRegion((String) value);
            }
        }
        ,
        Store {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStore();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setStore((String) value);
            }
        }
        ,
        StoreList {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStoreList();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setStoreList((String) value);
            }
        }
        ,
        StoreFormat {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStoreFormat();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setStoreFormat((String) value);
            }
        }
        ,
        Warehouse {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getWarehouse();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setWarehouse((String) value);
            }
        }
        ,
        WarehouseList {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getWarehouseList();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setWarehouseList((String) value);
            }
        }
        ,
        SelectionLevel {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSelectionLevel();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setSelectionLevel((String) value);
            }
        }
        ,
        Id {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getId();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setId((BigDecimal) value);
            }
        }
        ,
        DeptOrdFromSuppVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getDeptOrdFromSuppVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierListVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSupplierListVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DepartmentVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getDepartmentVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ClassVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getClassVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SubClassVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSubClassVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VpnVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getVpnVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VpnColourVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getVpnColourVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SkuVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getSkuVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemListVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getItemListVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getRegionVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreRegionVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStoreRegionVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreListVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStoreListVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreFormatVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getStoreFormatVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CrossDockWHVOA {
            public Object get(XDOrderScheduleSearchVORowImpl obj) {
                return obj.getCrossDockWHVOA();
            }

            public void put(XDOrderScheduleSearchVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XDOrderScheduleSearchVORowImpl object);

        public abstract void put(XDOrderScheduleSearchVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SUPPLIER = AttributesEnum.Supplier.index();
    public static final int SUPPLIERLIST = AttributesEnum.SupplierList.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int CLASS1 = AttributesEnum.Class1.index();
    public static final int SUBCLASS = AttributesEnum.Subclass.index();
    public static final int VPN = AttributesEnum.Vpn.index();
    public static final int STYLECOLOR = AttributesEnum.StyleColor.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int ITEMLIST = AttributesEnum.ItemList.index();
    public static final int REGION = AttributesEnum.Region.index();
    public static final int STORE = AttributesEnum.Store.index();
    public static final int STORELIST = AttributesEnum.StoreList.index();
    public static final int STOREFORMAT = AttributesEnum.StoreFormat.index();
    public static final int WAREHOUSE = AttributesEnum.Warehouse.index();
    public static final int WAREHOUSELIST = AttributesEnum.WarehouseList.index();
    public static final int SELECTIONLEVEL = AttributesEnum.SelectionLevel.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int DEPTORDFROMSUPPVOA = AttributesEnum.DeptOrdFromSuppVOA.index();
    public static final int SUPPLIERLISTVOA = AttributesEnum.SupplierListVOA.index();
    public static final int DEPARTMENTVOA = AttributesEnum.DepartmentVOA.index();
    public static final int CLASSVOA = AttributesEnum.ClassVOA.index();
    public static final int SUBCLASSVOA = AttributesEnum.SubClassVOA.index();
    public static final int VPNVOA = AttributesEnum.VpnVOA.index();
    public static final int VPNCOLOURVOA = AttributesEnum.VpnColourVOA.index();
    public static final int SKUVOA = AttributesEnum.SkuVOA.index();
    public static final int ITEMLISTVOA = AttributesEnum.ItemListVOA.index();
    public static final int REGIONVOA = AttributesEnum.RegionVOA.index();
    public static final int STOREREGIONVOA = AttributesEnum.StoreRegionVOA.index();
    public static final int STORELISTVOA = AttributesEnum.StoreListVOA.index();
    public static final int STOREFORMATVOA = AttributesEnum.StoreFormatVOA.index();
    public static final int CROSSDOCKWHVOA = AttributesEnum.CrossDockWHVOA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XDOrderScheduleSearchVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Supplier.
     * @return the Supplier
     */
    public String getSupplier() {
        return (String) getAttributeInternal(SUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Supplier.
     * @param value value to set the  Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierList.
     * @return the SupplierList
     */
    public String getSupplierList() {
        return (String) getAttributeInternal(SUPPLIERLIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierList.
     * @param value value to set the  SupplierList
     */
    public void setSupplierList(String value) {
        setAttributeInternal(SUPPLIERLIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Department.
     * @return the Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Department.
     * @param value value to set the  Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Class1.
     * @return the Class1
     */
    public String getClass1() {
        return (String) getAttributeInternal(CLASS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Class1.
     * @param value value to set the  Class1
     */
    public void setClass1(String value) {
        setAttributeInternal(CLASS1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Subclass.
     * @return the Subclass
     */
    public String getSubclass() {
        return (String) getAttributeInternal(SUBCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Subclass.
     * @param value value to set the  Subclass
     */
    public void setSubclass(String value) {
        setAttributeInternal(SUBCLASS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Vpn.
     * @return the Vpn
     */
    public String getVpn() {
        return (String) getAttributeInternal(VPN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Vpn.
     * @param value value to set the  Vpn
     */
    public void setVpn(String value) {
        setAttributeInternal(VPN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleColor.
     * @return the StyleColor
     */
    public String getStyleColor() {
        return (String) getAttributeInternal(STYLECOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleColor.
     * @param value value to set the  StyleColor
     */
    public void setStyleColor(String value) {
        setAttributeInternal(STYLECOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Item.
     * @return the Item
     */
    public String getItem() {
        return (String) getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Item.
     * @param value value to set the  Item
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemList.
     * @return the ItemList
     */
    public String getItemList() {
        return (String) getAttributeInternal(ITEMLIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemList.
     * @param value value to set the  ItemList
     */
    public void setItemList(String value) {
        setAttributeInternal(ITEMLIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Region.
     * @return the Region
     */
    public String getRegion() {
        return (String) getAttributeInternal(REGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Region.
     * @param value value to set the  Region
     */
    public void setRegion(String value) {
        setAttributeInternal(REGION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Store.
     * @return the Store
     */
    public String getStore() {
        return (String) getAttributeInternal(STORE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Store.
     * @param value value to set the  Store
     */
    public void setStore(String value) {
        setAttributeInternal(STORE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StoreList.
     * @return the StoreList
     */
    public String getStoreList() {
        return (String) getAttributeInternal(STORELIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StoreList.
     * @param value value to set the  StoreList
     */
    public void setStoreList(String value) {
        setAttributeInternal(STORELIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StoreFormat.
     * @return the StoreFormat
     */
    public String getStoreFormat() {
        return (String) getAttributeInternal(STOREFORMAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StoreFormat.
     * @param value value to set the  StoreFormat
     */
    public void setStoreFormat(String value) {
        setAttributeInternal(STOREFORMAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Warehouse.
     * @return the Warehouse
     */
    public String getWarehouse() {
        return (String) getAttributeInternal(WAREHOUSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Warehouse.
     * @param value value to set the  Warehouse
     */
    public void setWarehouse(String value) {
        setAttributeInternal(WAREHOUSE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseList.
     * @return the WarehouseList
     */
    public String getWarehouseList() {
        return (String) getAttributeInternal(WAREHOUSELIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseList.
     * @param value value to set the  WarehouseList
     */
    public void setWarehouseList(String value) {
        setAttributeInternal(WAREHOUSELIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectionLevel.
     * @return the SelectionLevel
     */
    public String getSelectionLevel() {
        return (String) getAttributeInternal(SELECTIONLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectionLevel.
     * @param value value to set the  SelectionLevel
     */
    public void setSelectionLevel(String value) {
        setAttributeInternal(SELECTIONLEVEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DeptOrdFromSuppVOA.
     */
    public RowSet getDeptOrdFromSuppVOA() {
        return (RowSet) getAttributeInternal(DEPTORDFROMSUPPVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierListVOA.
     */
    public RowSet getSupplierListVOA() {
        return (RowSet) getAttributeInternal(SUPPLIERLISTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartmentVOA.
     */
    public RowSet getDepartmentVOA() {
        return (RowSet) getAttributeInternal(DEPARTMENTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ClassVOA.
     */
    public RowSet getClassVOA() {
        return (RowSet) getAttributeInternal(CLASSVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubClassVOA.
     */
    public RowSet getSubClassVOA() {
        return (RowSet) getAttributeInternal(SUBCLASSVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VpnVOA.
     */
    public RowSet getVpnVOA() {
        return (RowSet) getAttributeInternal(VPNVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VpnColourVOA.
     */
    public RowSet getVpnColourVOA() {
        return (RowSet) getAttributeInternal(VPNCOLOURVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SkuVOA.
     */
    public RowSet getSkuVOA() {
        return (RowSet) getAttributeInternal(SKUVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemListVOA.
     */
    public RowSet getItemListVOA() {
        return (RowSet) getAttributeInternal(ITEMLISTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionVOA.
     */
    public RowSet getRegionVOA() {
        return (RowSet) getAttributeInternal(REGIONVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreRegionVOA.
     */
    public RowSet getStoreRegionVOA() {
        return (RowSet) getAttributeInternal(STOREREGIONVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreListVOA.
     */
    public RowSet getStoreListVOA() {
        return (RowSet) getAttributeInternal(STORELISTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreFormatVOA.
     */
    public RowSet getStoreFormatVOA() {
        return (RowSet) getAttributeInternal(STOREFORMATVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CrossDockWHVOA.
     */
    public RowSet getCrossDockWHVOA() {
        return (RowSet) getAttributeInternal(CROSSDOCKWHVOA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

