package oracle.retail.apps.aipdt.cnpd.model.applicationmodule.common;

import java.util.Date;
import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 16 18:04:42 IST 2016
// ---------------------------------------------------------------------
public interface CorporateNonPlanningDaysAM extends ApplicationModule {
    void initActivity();

    void filterDayTypeDropdown(String lookupType);

    String getIdsFromDtListDetailTable(Integer itemList, String TYPE);

    Map handleSearch(Map inputMap);

    void handleReset();

    void addRowOnResultVO();

    void deleteRowsFromResultVO();

    Map handleSave();

    void setAll(Date date);


    Boolean isTransactionDirty();
}

