package oracle.retail.apps.aipdt.listmaintain.model.applicationmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 26 16:01:52 IST 2016
// ---------------------------------------------------------------------
public interface SupplyChainListMaintainAM extends ApplicationModule {
    void initMaintainListActivity(String userName);

    void onClickResetAction();

    String onSearchClick();


    String saveMaintainList();

    void onfetchListDtls(oracle.jbo.domain.Number listId);
}

