package oracle.retail.apps.aipdt.rsos.model.view;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 30 15:23:18 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RsOrderScheduleProgVOImpl extends AipdtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RsOrderScheduleProgVOImpl() {
    }
}

