package oracle.retail.apps.aipdt.rc.model.view;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 24 22:09:36 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceivingCalendarSearchVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StockingPoint {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStockingPoint();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setStockingPoint((String)value);
            }
        }
        ,
        Store {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStore();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setStore((String)value);
            }
        }
        ,
        StoreFormat {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStoreFormat();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setStoreFormat((String)value);
            }
        }
        ,
        ProductType {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getProductType();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setProductType((String)value);
            }
        }
        ,
        LocationType {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getLocationType();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setLocationType((String)value);
            }
        }
        ,
        DefaultAttr {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getDefaultAttr();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setDefaultAttr((Boolean)value);
            }
        }
        ,
        ExceptionAttr {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getExceptionAttr();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setExceptionAttr((Boolean)value);
            }
        }
        ,
        StoreVOA {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStoreVOA();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StockingPointVOA {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStockingPointVOA();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreFormatVOA {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getStoreFormatVOA();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductTypeVOA {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getProductTypeVOA();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LocationTypeVOA {
            public Object get(ReceivingCalendarSearchVORowImpl obj) {
                return obj.getLocationTypeVOA();
            }

            public void put(ReceivingCalendarSearchVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ReceivingCalendarSearchVORowImpl object);

        public abstract void put(ReceivingCalendarSearchVORowImpl object,
                                 Object value);

        public int index() {
            return ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex() + ReceivingCalendarSearchVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = ReceivingCalendarSearchVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STOCKINGPOINT = ReceivingCalendarSearchVORowImpl.AttributesEnum.StockingPoint.index();
    public static final int STORE = ReceivingCalendarSearchVORowImpl.AttributesEnum.Store.index();
    public static final int STOREFORMAT = ReceivingCalendarSearchVORowImpl.AttributesEnum.StoreFormat.index();
    public static final int PRODUCTTYPE = ReceivingCalendarSearchVORowImpl.AttributesEnum.ProductType.index();
    public static final int LOCATIONTYPE = ReceivingCalendarSearchVORowImpl.AttributesEnum.LocationType.index();
    public static final int DEFAULTATTR = ReceivingCalendarSearchVORowImpl.AttributesEnum.DefaultAttr.index();
    public static final int EXCEPTIONATTR = ReceivingCalendarSearchVORowImpl.AttributesEnum.ExceptionAttr.index();
    public static final int STOREVOA = ReceivingCalendarSearchVORowImpl.AttributesEnum.StoreVOA.index();
    public static final int STOCKINGPOINTVOA = ReceivingCalendarSearchVORowImpl.AttributesEnum.StockingPointVOA.index();
    public static final int STOREFORMATVOA = ReceivingCalendarSearchVORowImpl.AttributesEnum.StoreFormatVOA.index();
    public static final int PRODUCTTYPEVOA = ReceivingCalendarSearchVORowImpl.AttributesEnum.ProductTypeVOA.index();
    public static final int LOCATIONTYPEVOA = ReceivingCalendarSearchVORowImpl.AttributesEnum.LocationTypeVOA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReceivingCalendarSearchVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StockingPoint.
     * @return the StockingPoint
     */
    public String getStockingPoint() {
        return (String) getAttributeInternal(STOCKINGPOINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StockingPoint.
     * @param value value to set the  StockingPoint
     */
    public void setStockingPoint(String value) {
        setAttributeInternal(STOCKINGPOINT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Store.
     * @return the Store
     */
    public String getStore() {
        return (String) getAttributeInternal(STORE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Store.
     * @param value value to set the  Store
     */
    public void setStore(String value) {
        setAttributeInternal(STORE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StoreFormat.
     * @return the StoreFormat
     */
    public String getStoreFormat() {
        return (String) getAttributeInternal(STOREFORMAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StoreFormat.
     * @param value value to set the  StoreFormat
     */
    public void setStoreFormat(String value) {
        setAttributeInternal(STOREFORMAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductType.
     * @return the ProductType
     */
    public String getProductType() {
        return (String) getAttributeInternal(PRODUCTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductType.
     * @param value value to set the  ProductType
     */
    public void setProductType(String value) {
        setAttributeInternal(PRODUCTTYPE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute LocationType.
     * @return the LocationType
     */
    public String getLocationType() {
        return (String) getAttributeInternal(LOCATIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LocationType.
     * @param value value to set the  LocationType
     */
    public void setLocationType(String value) {
        setAttributeInternal(LOCATIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DefaultAttr.
     * @return the DefaultAttr
     */
    public Boolean getDefaultAttr() {
        return (Boolean) getAttributeInternal(DEFAULTATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DefaultAttr.
     * @param value value to set the  DefaultAttr
     */
    public void setDefaultAttr(Boolean value) {
        setAttributeInternal(DEFAULTATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExceptionAttr.
     * @return the ExceptionAttr
     */
    public Boolean getExceptionAttr() {
        return (Boolean) getAttributeInternal(EXCEPTIONATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExceptionAttr.
     * @param value value to set the  ExceptionAttr
     */
    public void setExceptionAttr(Boolean value) {
        setAttributeInternal(EXCEPTIONATTR, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreVOA.
     */
    public RowSet getStoreVOA() {
        return (RowSet)getAttributeInternal(STOREVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StockingPointVOA.
     */
    public RowSet getStockingPointVOA() {
        return (RowSet)getAttributeInternal(STOCKINGPOINTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreFormatVOA.
     */
    public RowSet getStoreFormatVOA() {
        return (RowSet)getAttributeInternal(STOREFORMATVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductTypeVOA.
     */
    public RowSet getProductTypeVOA() {
        return (RowSet)getAttributeInternal(PRODUCTTYPEVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocationTypeVOA.
     */
    public RowSet getLocationTypeVOA() {
        return (RowSet)getAttributeInternal(LOCATIONTYPEVOA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex()) && (index < ReceivingCalendarSearchVORowImpl.AttributesEnum.count())) {
            return ReceivingCalendarSearchVORowImpl.AttributesEnum.staticValues()[index - ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex()) && (index < ReceivingCalendarSearchVORowImpl.AttributesEnum.count())) {
            ReceivingCalendarSearchVORowImpl.AttributesEnum.staticValues()[index - ReceivingCalendarSearchVORowImpl.AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
