package oracle.retail.apps.aipdt.common.model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 08 16:39:36 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DateParamVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Vdate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getVdate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setVdate((Date)value);
            }
        }
        ,
        DtStartEndDateParam {
            public Object get(DateParamVORowImpl obj) {
                return obj.getDtStartEndDateParam();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setDtStartEndDateParam((Number)value);
            }
        }
        ,
        SystemHighDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getSystemHighDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setSystemHighDate((Date)value);
            }
        }
        ,
        MinStartDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getMinStartDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setMinStartDate((Date)value);
            }
        }
        ,
        MaxStartDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getMaxStartDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setMaxStartDate((Date)value);
            }
        }
        ,
        MinEndDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getMinEndDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setMinEndDate((Date)value);
            }
        }
        ,
        MaxEndDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getMaxEndDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setMaxEndDate((Date)value);
            }
        }
        ,
        VdatePlusOne {
            public Object get(DateParamVORowImpl obj) {
                return obj.getVdatePlusOne();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setVdatePlusOne((Date)value);
            }
        }
        ,
        SystemDate {
            public Object get(DateParamVORowImpl obj) {
                return obj.getSystemDate();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setSystemDate((Date)value);
            }
        }
        ,
        SystemDatePlusOne {
            public Object get(DateParamVORowImpl obj) {
                return obj.getSystemDatePlusOne();
            }

            public void put(DateParamVORowImpl obj, Object value) {
                obj.setSystemDatePlusOne((Date)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DateParamVORowImpl object);

        public abstract void put(DateParamVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int VDATE = AttributesEnum.Vdate.index();
    public static final int DTSTARTENDDATEPARAM = AttributesEnum.DtStartEndDateParam.index();
    public static final int SYSTEMHIGHDATE = AttributesEnum.SystemHighDate.index();
    public static final int MINSTARTDATE = AttributesEnum.MinStartDate.index();
    public static final int MAXSTARTDATE = AttributesEnum.MaxStartDate.index();
    public static final int MINENDDATE = AttributesEnum.MinEndDate.index();
    public static final int MAXENDDATE = AttributesEnum.MaxEndDate.index();
    public static final int VDATEPLUSONE = AttributesEnum.VdatePlusOne.index();
    public static final int SYSTEMDATE = AttributesEnum.SystemDate.index();
    public static final int SYSTEMDATEPLUSONE = AttributesEnum.SystemDatePlusOne.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DateParamVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Vdate.
     * @return the Vdate
     */
    public Date getVdate() {
        return (Date)getAttributeInternal(VDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Vdate.
     * @param value value to set the  Vdate
     */
    public void setVdate(Date value) {
        setAttributeInternal(VDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DtStartEndDateParam.
     * @return the DtStartEndDateParam
     */
    public Number getDtStartEndDateParam() {
        return (Number)getAttributeInternal(DTSTARTENDDATEPARAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DtStartEndDateParam.
     * @param value value to set the  DtStartEndDateParam
     */
    public void setDtStartEndDateParam(Number value) {
        setAttributeInternal(DTSTARTENDDATEPARAM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SystemHighDate.
     * @return the SystemHighDate
     */
    public Date getSystemHighDate() {
        return (Date)getAttributeInternal(SYSTEMHIGHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SystemHighDate.
     * @param value value to set the  SystemHighDate
     */
    public void setSystemHighDate(Date value) {
        setAttributeInternal(SYSTEMHIGHDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MinStartDate.
     * @return the MinStartDate
     */
    public Date getMinStartDate() {
        return (Date)getAttributeInternal(MINSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MinStartDate.
     * @param value value to set the  MinStartDate
     */
    public void setMinStartDate(Date value) {
        setAttributeInternal(MINSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MaxStartDate.
     * @return the MaxStartDate
     */
    public Date getMaxStartDate() {
        return (Date)getAttributeInternal(MAXSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MaxStartDate.
     * @param value value to set the  MaxStartDate
     */
    public void setMaxStartDate(Date value) {
        setAttributeInternal(MAXSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MinEndDate.
     * @return the MinEndDate
     */
    public Date getMinEndDate() {
        return (Date)getAttributeInternal(MINENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MinEndDate.
     * @param value value to set the  MinEndDate
     */
    public void setMinEndDate(Date value) {
        setAttributeInternal(MINENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MaxEndDate.
     * @return the MaxEndDate
     */
    public Date getMaxEndDate() {
        return (Date)getAttributeInternal(MAXENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MaxEndDate.
     * @param value value to set the  MaxEndDate
     */
    public void setMaxEndDate(Date value) {
        setAttributeInternal(MAXENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VdatePlusOne.
     * @return the VdatePlusOne
     */
    public Date getVdatePlusOne() {
        return (Date)getAttributeInternal(VDATEPLUSONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VdatePlusOne.
     * @param value value to set the  VdatePlusOne
     */
    public void setVdatePlusOne(Date value) {
        setAttributeInternal(VDATEPLUSONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SystemDate.
     * @return the SystemDate
     */
    public Date getSystemDate() {
        return (Date)getAttributeInternal(SYSTEMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SystemDate.
     * @param value value to set the  SystemDate
     */
    public void setSystemDate(Date value) {
        setAttributeInternal(SYSTEMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SystemDatePlusOne.
     * @return the SystemDatePlusOne
     */
    public Date getSystemDatePlusOne() {
        return (Date)getAttributeInternal(SYSTEMDATEPLUSONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SystemDatePlusOne.
     * @param value value to set the  SystemDatePlusOne
     */
    public void setSystemDatePlusOne(Date value) {
        setAttributeInternal(SYSTEMDATEPLUSONE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
