package oracle.retail.apps.aipdt.common.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 16:38:23 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemListVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ListId {
            public Object get(ItemListVORowImpl obj) {
                return obj.getListId();
            }

            public void put(ItemListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ListName {
            public Object get(ItemListVORowImpl obj) {
                return obj.getListName();
            }

            public void put(ItemListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ItemListVORowImpl object);

        public abstract void put(ItemListVORowImpl object, Object value);

        public int index() {
            return ItemListVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return ItemListVORowImpl.AttributesEnum.firstIndex() + ItemListVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = ItemListVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LISTID = AttributesEnum.ListId.index();
    public static final int LISTNAME = AttributesEnum.ListName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ItemListVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ListId.
     * @return the ListId
     */
    public Number getListId() {
        return (Number) getAttributeInternal(LISTID);
    }


    /**
     * Gets the attribute value for the calculated attribute ListName.
     * @return the ListName
     */
    public String getListName() {
        return (String) getAttributeInternal(LISTNAME);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
