package oracle.retail.apps.aipdt.common.model.view;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 31 19:49:14 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionVODefImpl extends AipdtViewDefImpl {
    public RegionVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public RegionVODefImpl() {
    }
}

