package oracle.retail.apps.aipdt.common.model.view;

import java.math.BigDecimal;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 31 19:49:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RegionId {
            public Object get(RegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(RegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionCode {
            public Object get(RegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(RegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionDesc {
            public Object get(RegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(RegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(RegionVORowImpl object);

        public abstract void put(RegionVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int REGIONDESC = AttributesEnum.RegionDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RegionVORowImpl() {
    }
}

