package oracle.retail.apps.aipdt.common.model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 08 10:46:16 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StockingPointVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WarehouseCode,
        WarehouseId,
        WarehouseName,
        WarehouseType,
        Id;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return StockingPointVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return StockingPointVORowImpl.AttributesEnum.firstIndex() + StockingPointVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = StockingPointVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WAREHOUSECODE = AttributesEnum.WarehouseCode.index();
    public static final int WAREHOUSEID = AttributesEnum.WarehouseId.index();
    public static final int WAREHOUSENAME = AttributesEnum.WarehouseName.index();
    public static final int WAREHOUSETYPE = AttributesEnum.WarehouseType.index();
    public static final int ID = AttributesEnum.Id.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StockingPointVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseCode.
     * @return the WarehouseCode
     */
    public String getWarehouseCode() {
        return (String) getAttributeInternal(WAREHOUSECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseCode.
     * @param value value to set the  WarehouseCode
     */
    public void setWarehouseCode(String value) {
        setAttributeInternal(WAREHOUSECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseId.
     * @return the WarehouseId
     */
    public Number getWarehouseId() {
        return (Number)getAttributeInternal(WAREHOUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseId.
     * @param value value to set the  WarehouseId
     */
    public void setWarehouseId(Number value) {
        setAttributeInternal(WAREHOUSEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseName.
     * @return the WarehouseName
     */
    public String getWarehouseName() {
        return (String) getAttributeInternal(WAREHOUSENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseName.
     * @param value value to set the  WarehouseName
     */
    public void setWarehouseName(String value) {
        setAttributeInternal(WAREHOUSENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseType.
     * @return the WarehouseType
     */
    public String getWarehouseType() {
        return (String) getAttributeInternal(WAREHOUSETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseType.
     * @param value value to set the  WarehouseType
     */
    public void setWarehouseType(String value) {
        setAttributeInternal(WAREHOUSETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }
}
