package oracle.retail.apps.aipdt.common.model.view;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 21 17:34:04 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StoreVOImpl extends AipdtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StoreVOImpl() {
    }


    /**
     * Returns the variable value for regId.
     * @return variable value for regId
     */
    public Integer getregId() {
        return (Integer) ensureVariableManager().getVariableValue("regId");
    }

    /**
     * Sets <code>value</code> for variable regId.
     * @param value value to bind as regId
     */
    public void setregId(Integer value) {
        ensureVariableManager().setVariableValue("regId", value);
    }
}
