package oracle.retail.apps.aipdt.common.model.view;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 03 17:17:29 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StoreRegionVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StoreCode {
            public Object get(StoreRegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(StoreRegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreId {
            public Object get(StoreRegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(StoreRegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreName {
            public Object get(StoreRegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(StoreRegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionId {
            public Object get(StoreRegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(StoreRegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Id {
            public Object get(StoreRegionVORowImpl obj) {
                return obj.getAttributeInternal(index());
            }

            public void put(StoreRegionVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(StoreRegionVORowImpl object);

        public abstract void put(StoreRegionVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STORECODE = AttributesEnum.StoreCode.index();
    public static final int STOREID = AttributesEnum.StoreId.index();
    public static final int STORENAME = AttributesEnum.StoreName.index();
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int ID = AttributesEnum.Id.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StoreRegionVORowImpl() {
    }
}

