package oracle.retail.apps.aipdt.np.model.applicationmodule.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 05 11:54:04 IST 2016
// ---------------------------------------------------------------------
public interface NetworkPathAM extends ApplicationModule {
    long handleCheckBoxAll(boolean isSelected);

    void handleReset();

    void handleSetAll(Map<String, Object> setAllMap);

    boolean handleSelect() throws Exception;
    
    void saveNetworkPath() throws Exception;
}

