package oracle.retail.apps.aipdt.rswspm.model.view;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtEntityImpl;
import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 15 15:04:57 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StorePriorityMatrixVORowImpl extends AipdtViewRowImpl {

    public static final int ENTITY_STOREPRIORITYMATRIXEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreateDate {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getCreateDate();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setCreateDate((Date) value);
            }
        }
        ,
        CreateUser {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getCreateUser();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setCreateUser((String) value);
            }
        }
        ,
        Id {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getId();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setId((Number) value);
            }
        }
        ,
        StockingPointCode1 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointCode1();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointCode1((String) value);
            }
        }
        ,
        StockingPointCode2 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointCode2();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointCode2((String) value);
            }
        }
        ,
        StockingPointCode3 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointCode3();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointCode3((String) value);
            }
        }
        ,
        StockingPointDesc1 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointDesc1();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointDesc1((String) value);
            }
        }
        ,
        StockingPointDesc2 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointDesc2();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointDesc2((String) value);
            }
        }
        ,
        StockingPointDesc3 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointDesc3();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointDesc3((String) value);
            }
        }
        ,
        StockingPointId1 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointId1();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointId1((Number) value);
            }
        }
        ,
        StockingPointId2 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointId2();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointId2((Number) value);
            }
        }
        ,
        StockingPointId3 {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointId3();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStockingPointId3((Number) value);
            }
        }
        ,
        StoreCode {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStoreCode();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStoreCode((String) value);
            }
        }
        ,
        StoreDesc {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStoreDesc();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStoreDesc((String) value);
            }
        }
        ,
        StoreId {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStoreId();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setStoreId((Number) value);
            }
        }
        ,
        TransactionId {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getTransactionId();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setTransactionId((Number) value);
            }
        }
        ,
        UpdateInd {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getUpdateInd();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setUpdateInd((String) value);
            }
        }
        ,
        StockingPointVOA {
            public Object get(StorePriorityMatrixVORowImpl obj) {
                return obj.getStockingPointVOA();
            }

            public void put(StorePriorityMatrixVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(StorePriorityMatrixVORowImpl object);

        public abstract void put(StorePriorityMatrixVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int CREATEUSER = AttributesEnum.CreateUser.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int STOCKINGPOINTCODE1 = AttributesEnum.StockingPointCode1.index();
    public static final int STOCKINGPOINTCODE2 = AttributesEnum.StockingPointCode2.index();
    public static final int STOCKINGPOINTCODE3 = AttributesEnum.StockingPointCode3.index();
    public static final int STOCKINGPOINTDESC1 = AttributesEnum.StockingPointDesc1.index();
    public static final int STOCKINGPOINTDESC2 = AttributesEnum.StockingPointDesc2.index();
    public static final int STOCKINGPOINTDESC3 = AttributesEnum.StockingPointDesc3.index();
    public static final int STOCKINGPOINTID1 = AttributesEnum.StockingPointId1.index();
    public static final int STOCKINGPOINTID2 = AttributesEnum.StockingPointId2.index();
    public static final int STOCKINGPOINTID3 = AttributesEnum.StockingPointId3.index();
    public static final int STORECODE = AttributesEnum.StoreCode.index();
    public static final int STOREDESC = AttributesEnum.StoreDesc.index();
    public static final int STOREID = AttributesEnum.StoreId.index();
    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int UPDATEIND = AttributesEnum.UpdateInd.index();
    public static final int STOCKINGPOINTVOA = AttributesEnum.StockingPointVOA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StorePriorityMatrixVORowImpl() {
    }

    /**
     * Gets StorePriorityMatrixEO entity object.
     * @return the StorePriorityMatrixEO
     */
    public AipdtEntityImpl getStorePriorityMatrixEO() {
        return (AipdtEntityImpl) getEntity(ENTITY_STOREPRIORITYMATRIXEO);
    }

    /**
     * Gets the attribute value for CREATE_DATE using the alias name CreateDate.
     * @return the CREATE_DATE
     */
    public Date getCreateDate() {
        return (Date) getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_DATE using the alias name CreateDate.
     * @param value value to set the CREATE_DATE
     */
    public void setCreateDate(Date value) {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for CREATE_USER using the alias name CreateUser.
     * @return the CREATE_USER
     */
    public String getCreateUser() {
        return (String) getAttributeInternal(CREATEUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_USER using the alias name CreateUser.
     * @param value value to set the CREATE_USER
     */
    public void setCreateUser(String value) {
        setAttributeInternal(CREATEUSER, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_CODE_1 using the alias name StockingPointCode1.
     * @return the STOCKING_POINT_CODE_1
     */
    public String getStockingPointCode1() {
        return (String) getAttributeInternal(STOCKINGPOINTCODE1);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_CODE_1 using the alias name StockingPointCode1.
     * @param value value to set the STOCKING_POINT_CODE_1
     */
    public void setStockingPointCode1(String value) {
        setAttributeInternal(STOCKINGPOINTCODE1, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_CODE_2 using the alias name StockingPointCode2.
     * @return the STOCKING_POINT_CODE_2
     */
    public String getStockingPointCode2() {
        return (String) getAttributeInternal(STOCKINGPOINTCODE2);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_CODE_2 using the alias name StockingPointCode2.
     * @param value value to set the STOCKING_POINT_CODE_2
     */
    public void setStockingPointCode2(String value) {
        setAttributeInternal(STOCKINGPOINTCODE2, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_CODE_3 using the alias name StockingPointCode3.
     * @return the STOCKING_POINT_CODE_3
     */
    public String getStockingPointCode3() {
        return (String) getAttributeInternal(STOCKINGPOINTCODE3);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_CODE_3 using the alias name StockingPointCode3.
     * @param value value to set the STOCKING_POINT_CODE_3
     */
    public void setStockingPointCode3(String value) {
        setAttributeInternal(STOCKINGPOINTCODE3, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_DESC_1 using the alias name StockingPointDesc1.
     * @return the STOCKING_POINT_DESC_1
     */
    public String getStockingPointDesc1() {
        return (String) getAttributeInternal(STOCKINGPOINTDESC1);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_DESC_1 using the alias name StockingPointDesc1.
     * @param value value to set the STOCKING_POINT_DESC_1
     */
    public void setStockingPointDesc1(String value) {
        setAttributeInternal(STOCKINGPOINTDESC1, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_DESC_2 using the alias name StockingPointDesc2.
     * @return the STOCKING_POINT_DESC_2
     */
    public String getStockingPointDesc2() {
        return (String) getAttributeInternal(STOCKINGPOINTDESC2);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_DESC_2 using the alias name StockingPointDesc2.
     * @param value value to set the STOCKING_POINT_DESC_2
     */
    public void setStockingPointDesc2(String value) {
        setAttributeInternal(STOCKINGPOINTDESC2, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_DESC_3 using the alias name StockingPointDesc3.
     * @return the STOCKING_POINT_DESC_3
     */
    public String getStockingPointDesc3() {
        return (String) getAttributeInternal(STOCKINGPOINTDESC3);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_DESC_3 using the alias name StockingPointDesc3.
     * @param value value to set the STOCKING_POINT_DESC_3
     */
    public void setStockingPointDesc3(String value) {
        setAttributeInternal(STOCKINGPOINTDESC3, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_ID_1 using the alias name StockingPointId1.
     * @return the STOCKING_POINT_ID_1
     */
    public Number getStockingPointId1() {
        return (Number) getAttributeInternal(STOCKINGPOINTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_ID_1 using the alias name StockingPointId1.
     * @param value value to set the STOCKING_POINT_ID_1
     */
    public void setStockingPointId1(Number value) {
        setAttributeInternal(STOCKINGPOINTID1, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_ID_2 using the alias name StockingPointId2.
     * @return the STOCKING_POINT_ID_2
     */
    public Number getStockingPointId2() {
        return (Number) getAttributeInternal(STOCKINGPOINTID2);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_ID_2 using the alias name StockingPointId2.
     * @param value value to set the STOCKING_POINT_ID_2
     */
    public void setStockingPointId2(Number value) {
        setAttributeInternal(STOCKINGPOINTID2, value);
    }

    /**
     * Gets the attribute value for STOCKING_POINT_ID_3 using the alias name StockingPointId3.
     * @return the STOCKING_POINT_ID_3
     */
    public Number getStockingPointId3() {
        return (Number) getAttributeInternal(STOCKINGPOINTID3);
    }

    /**
     * Sets <code>value</code> as attribute value for STOCKING_POINT_ID_3 using the alias name StockingPointId3.
     * @param value value to set the STOCKING_POINT_ID_3
     */
    public void setStockingPointId3(Number value) {
        setAttributeInternal(STOCKINGPOINTID3, value);
    }

    /**
     * Gets the attribute value for STORE_CODE using the alias name StoreCode.
     * @return the STORE_CODE
     */
    public String getStoreCode() {
        return (String) getAttributeInternal(STORECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for STORE_CODE using the alias name StoreCode.
     * @param value value to set the STORE_CODE
     */
    public void setStoreCode(String value) {
        setAttributeInternal(STORECODE, value);
    }

    /**
     * Gets the attribute value for STORE_DESC using the alias name StoreDesc.
     * @return the STORE_DESC
     */
    public String getStoreDesc() {
        return (String) getAttributeInternal(STOREDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for STORE_DESC using the alias name StoreDesc.
     * @param value value to set the STORE_DESC
     */
    public void setStoreDesc(String value) {
        setAttributeInternal(STOREDESC, value);
    }

    /**
     * Gets the attribute value for STORE_ID using the alias name StoreId.
     * @return the STORE_ID
     */
    public Number getStoreId() {
        return (Number) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STORE_ID using the alias name StoreId.
     * @param value value to set the STORE_ID
     */
    public void setStoreId(Number value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @return the TRANSACTION_ID
     */
    public Number getTransactionId() {
        return (Number) getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @param value value to set the TRANSACTION_ID
     */
    public void setTransactionId(Number value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for UPDATE_IND using the alias name UpdateInd.
     * @return the UPDATE_IND
     */
    public String getUpdateInd() {
        return (String) getAttributeInternal(UPDATEIND);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_IND using the alias name UpdateInd.
     * @param value value to set the UPDATE_IND
     */
    public void setUpdateInd(String value) {
        setAttributeInternal(UPDATEIND, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StockingPointVOA.
     */
    public RowSet getStockingPointVOA() {
        return (RowSet) getAttributeInternal(STOCKINGPOINTVOA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

