package oracle.retail.apps.aipdt.dt.model.view;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 11 10:57:26 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeploymentTypeSearchRVODefImpl extends AipdtViewDefImpl {
    public DeploymentTypeSearchRVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public DeploymentTypeSearchRVODefImpl() {
    }
}
