package oracle.retail.apps.aipdt.listcreate.model.view;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 24 11:57:54 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SupplyListCreationProgVORowImpl extends AipdtViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WorkingLevelAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getWorkingLevelAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setWorkingLevelAttr((String) value);
            }
        }
        ,
        ListNameAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getListNameAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setListNameAttr((String) value);
            }
        }
        ,
        ListPrivacyAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getListPrivacyAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setListPrivacyAttr((String) value);
            }
        }
        ,
        Department {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getDepartment();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setDepartment((Number) value);
            }
        }
        ,
        ClassIdAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getClassIdAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setClassIdAttr((String) value);
            }
        }
        ,
        SubClassIdAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSubClassIdAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setSubClassIdAttr((String) value);
            }
        }
        ,
        VPN {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getVPN();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setVPN((String) value);
            }
        }
        ,
        VPNOrColorCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getVPNOrColorCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setVPNOrColorCodeAttr((String) value);
            }
        }
        ,
        SKUCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSKUCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setSKUCodeAttr((String) value);
            }
        }
        ,
        SupplierCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSupplierCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setSupplierCodeAttr((String) value);
            }
        }
        ,
        StoreCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getStoreCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setStoreCodeAttr((String) value);
            }
        }
        ,
        WarehouseCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getWarehouseCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setWarehouseCodeAttr((String) value);
            }
        }
        ,
        RowVal {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getRowVal();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setRowVal((String) value);
            }
        }
        ,
        RegionCodeAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getRegionCodeAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setRegionCodeAttr((String) value);
            }
        }
        ,
        RegionIdAttr {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getRegionIdAttr();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setRegionIdAttr((Number) value);
            }
        }
        ,
        DepartmentVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getDepartmentVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VpnVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getVpnVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WorkingLevelTypeVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getWorkingLevelTypeVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WorkingPrivacyVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getWorkingPrivacyVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ClassVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getClassVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SubClassVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSubClassVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VpnColourVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getVpnColourVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SkuVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSkuVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierListVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSupplierListVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getSupplierVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StoreRegionVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getStoreRegionVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StockingPointVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getStockingPointVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionVOA {
            public Object get(SupplyListCreationProgVORowImpl obj) {
                return obj.getRegionVOA();
            }

            public void put(SupplyListCreationProgVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public abstract Object get(SupplyListCreationProgVORowImpl object);

        public abstract void put(SupplyListCreationProgVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WORKINGLEVELATTR = AttributesEnum.WorkingLevelAttr.index();
    public static final int LISTNAMEATTR = AttributesEnum.ListNameAttr.index();
    public static final int LISTPRIVACYATTR = AttributesEnum.ListPrivacyAttr.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int CLASSIDATTR = AttributesEnum.ClassIdAttr.index();
    public static final int SUBCLASSIDATTR = AttributesEnum.SubClassIdAttr.index();
    public static final int VPN = AttributesEnum.VPN.index();
    public static final int VPNORCOLORCODEATTR = AttributesEnum.VPNOrColorCodeAttr.index();
    public static final int SKUCODEATTR = AttributesEnum.SKUCodeAttr.index();
    public static final int SUPPLIERCODEATTR = AttributesEnum.SupplierCodeAttr.index();
    public static final int STORECODEATTR = AttributesEnum.StoreCodeAttr.index();
    public static final int WAREHOUSECODEATTR = AttributesEnum.WarehouseCodeAttr.index();
    public static final int ROWVAL = AttributesEnum.RowVal.index();
    public static final int REGIONCODEATTR = AttributesEnum.RegionCodeAttr.index();
    public static final int REGIONIDATTR = AttributesEnum.RegionIdAttr.index();
    public static final int DEPARTMENTVOA = AttributesEnum.DepartmentVOA.index();
    public static final int VPNVOA = AttributesEnum.VpnVOA.index();
    public static final int WORKINGLEVELTYPEVOA = AttributesEnum.WorkingLevelTypeVOA.index();
    public static final int WORKINGPRIVACYVOA = AttributesEnum.WorkingPrivacyVOA.index();
    public static final int CLASSVOA = AttributesEnum.ClassVOA.index();
    public static final int SUBCLASSVOA = AttributesEnum.SubClassVOA.index();
    public static final int VPNCOLOURVOA = AttributesEnum.VpnColourVOA.index();
    public static final int SKUVOA = AttributesEnum.SkuVOA.index();
    public static final int SUPPLIERLISTVOA = AttributesEnum.SupplierListVOA.index();
    public static final int SUPPLIERVOA = AttributesEnum.SupplierVOA.index();
    public static final int STOREREGIONVOA = AttributesEnum.StoreRegionVOA.index();
    public static final int STOCKINGPOINTVOA = AttributesEnum.StockingPointVOA.index();
    public static final int REGIONVOA = AttributesEnum.RegionVOA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SupplyListCreationProgVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WorkingLevelAttr.
     * @return the WorkingLevelAttr
     */
    public String getWorkingLevelAttr() {
        return (String) getAttributeInternal(WORKINGLEVELATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WorkingLevelAttr.
     * @param value value to set the  WorkingLevelAttr
     */
    public void setWorkingLevelAttr(String value) {
        setAttributeInternal(WORKINGLEVELATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ListNameAttr.
     * @return the ListNameAttr
     */
    public String getListNameAttr() {
        return (String) getAttributeInternal(LISTNAMEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ListNameAttr.
     * @param value value to set the  ListNameAttr
     */
    public void setListNameAttr(String value) {
        setAttributeInternal(LISTNAMEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ListPrivacyAttr.
     * @return the ListPrivacyAttr
     */
    public String getListPrivacyAttr() {
        return (String) getAttributeInternal(LISTPRIVACYATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ListPrivacyAttr.
     * @param value value to set the  ListPrivacyAttr
     */
    public void setListPrivacyAttr(String value) {
        setAttributeInternal(LISTPRIVACYATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Department.
     * @return the Department
     */
    public Number getDepartment() {
        return (Number) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Department.
     * @param value value to set the  Department
     */
    public void setDepartment(Number value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ClassIdAttr.
     * @return the ClassIdAttr
     */
    public String getClassIdAttr() {
        return (String) getAttributeInternal(CLASSIDATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ClassIdAttr.
     * @param value value to set the  ClassIdAttr
     */
    public void setClassIdAttr(String value) {
        setAttributeInternal(CLASSIDATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubClassIdAttr.
     * @return the SubClassIdAttr
     */
    public String getSubClassIdAttr() {
        return (String) getAttributeInternal(SUBCLASSIDATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubClassIdAttr.
     * @param value value to set the  SubClassIdAttr
     */
    public void setSubClassIdAttr(String value) {
        setAttributeInternal(SUBCLASSIDATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VPN.
     * @return the VPN
     */
    public String getVPN() {
        return (String) getAttributeInternal(VPN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VPN.
     * @param value value to set the  VPN
     */
    public void setVPN(String value) {
        setAttributeInternal(VPN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VPNOrColorCodeAttr.
     * @return the VPNOrColorCodeAttr
     */
    public String getVPNOrColorCodeAttr() {
        return (String) getAttributeInternal(VPNORCOLORCODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VPNOrColorCodeAttr.
     * @param value value to set the  VPNOrColorCodeAttr
     */
    public void setVPNOrColorCodeAttr(String value) {
        setAttributeInternal(VPNORCOLORCODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SKUCodeAttr.
     * @return the SKUCodeAttr
     */
    public String getSKUCodeAttr() {
        return (String) getAttributeInternal(SKUCODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SKUCodeAttr.
     * @param value value to set the  SKUCodeAttr
     */
    public void setSKUCodeAttr(String value) {
        setAttributeInternal(SKUCODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupplierCodeAttr.
     * @return the SupplierCodeAttr
     */
    public String getSupplierCodeAttr() {
        return (String) getAttributeInternal(SUPPLIERCODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupplierCodeAttr.
     * @param value value to set the  SupplierCodeAttr
     */
    public void setSupplierCodeAttr(String value) {
        setAttributeInternal(SUPPLIERCODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StoreCodeAttr.
     * @return the StoreCodeAttr
     */
    public String getStoreCodeAttr() {
        return (String) getAttributeInternal(STORECODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StoreCodeAttr.
     * @param value value to set the  StoreCodeAttr
     */
    public void setStoreCodeAttr(String value) {
        setAttributeInternal(STORECODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WarehouseCodeAttr.
     * @return the WarehouseCodeAttr
     */
    public String getWarehouseCodeAttr() {
        return (String) getAttributeInternal(WAREHOUSECODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarehouseCodeAttr.
     * @param value value to set the  WarehouseCodeAttr
     */
    public void setWarehouseCodeAttr(String value) {
        setAttributeInternal(WAREHOUSECODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowVal.
     * @return the RowVal
     */
    public String getRowVal() {
        return (String) getAttributeInternal(ROWVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowVal.
     * @param value value to set the  RowVal
     */
    public void setRowVal(String value) {
        setAttributeInternal(ROWVAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegionCodeAttr.
     * @return the RegionCodeAttr
     */
    public String getRegionCodeAttr() {
        return (String) getAttributeInternal(REGIONCODEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegionCodeAttr.
     * @param value value to set the  RegionCodeAttr
     */
    public void setRegionCodeAttr(String value) {
        setAttributeInternal(REGIONCODEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegionIdAttr.
     * @return the RegionIdAttr
     */
    public Number getRegionIdAttr() {
        return (Number) getAttributeInternal(REGIONIDATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegionIdAttr.
     * @param value value to set the  RegionIdAttr
     */
    public void setRegionIdAttr(Number value) {
        setAttributeInternal(REGIONIDATTR, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> DepartmentVOA.
     */
    public RowSet getDepartmentVOA() {
        return (RowSet) getAttributeInternal(DEPARTMENTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VpnVOA.
     */
    public RowSet getVpnVOA() {
        return (RowSet) getAttributeInternal(VPNVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WorkingLevelTypeVOA.
     */
    public RowSet getWorkingLevelTypeVOA() {
        return (RowSet) getAttributeInternal(WORKINGLEVELTYPEVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WorkingPrivacyVOA.
     */
    public RowSet getWorkingPrivacyVOA() {
        return (RowSet) getAttributeInternal(WORKINGPRIVACYVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ClassVOA.
     */
    public RowSet getClassVOA() {
        return (RowSet) getAttributeInternal(CLASSVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubClassVOA.
     */
    public RowSet getSubClassVOA() {
        return (RowSet) getAttributeInternal(SUBCLASSVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VpnColourVOA.
     */
    public RowSet getVpnColourVOA() {
        return (RowSet) getAttributeInternal(VPNCOLOURVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SkuVOA.
     */
    public RowSet getSkuVOA() {
        return (RowSet) getAttributeInternal(SKUVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierListVOA.
     */
    public RowSet getSupplierListVOA() {
        return (RowSet) getAttributeInternal(SUPPLIERLISTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierVOA.
     */
    public RowSet getSupplierVOA() {
        return (RowSet) getAttributeInternal(SUPPLIERVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StoreRegionVOA.
     */
    public RowSet getStoreRegionVOA() {
        return (RowSet) getAttributeInternal(STOREREGIONVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StockingPointVOA.
     */
    public RowSet getStockingPointVOA() {
        return (RowSet) getAttributeInternal(STOCKINGPOINTVOA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionVOA.
     */
    public RowSet getRegionVOA() {
        return (RowSet) getAttributeInternal(REGIONVOA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

