package oracle.retail.apps.aipdt.rc.model.applicationmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 27 14:46:13 IST 2015
// ---------------------------------------------------------------------
public interface ReceivingCalendarAM extends ApplicationModule {

    void initReceivingCalendar();

    void saveReceivingCalendar();

    boolean handleSelect();

    void handleReset();
}
