package oracle.retail.apps.aipdt.osos.model.entity;

import java.math.BigDecimal;

import java.sql.Date;

import java.util.ArrayList;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.retail.apps.aipdt.common.adfbc.AipdtEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 24 14:03:57 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OnOffSaleSupplyResultsEOImpl extends AipdtEntityImpl {
    /**
     * Validation method for Check1.
     */
    public boolean validateCheck1(Boolean check1) {
        return true;
    }

    /**
     * Validation method for OnOffSaleSupplyResultsEO.
     */
    public boolean validateOnOffSaleSupplyResultsEO1(ArrayList ctxList) {
        
        return true;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setId((BigDecimal) value);
            }
        }
        ,
        DeptId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getDeptId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setDeptId((BigDecimal) value);
            }
        }
        ,
        DeptCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getDeptCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setDeptCode((String) value);
            }
        }
        ,
        DeptName {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getDeptName();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setDeptName((String) value);
            }
        }
        ,
        ClassId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getClassId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setClassId((BigDecimal) value);
            }
        }
        ,
        ClassCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getClassCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setClassCode((String) value);
            }
        }
        ,
        ClassName {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getClassName();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setClassName((String) value);
            }
        }
        ,
        SubclassId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSubclassId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSubclassId((BigDecimal) value);
            }
        }
        ,
        SubclassCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSubclassCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSubclassCode((String) value);
            }
        }
        ,
        SubclassName {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSubclassName();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSubclassName((String) value);
            }
        }
        ,
        VpnId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnId((BigDecimal) value);
            }
        }
        ,
        VpnCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnCode((String) value);
            }
        }
        ,
        VpnDesc {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnDesc();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnDesc((String) value);
            }
        }
        ,
        VpnColorId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnColorId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnColorId((BigDecimal) value);
            }
        }
        ,
        VpnColorCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnColorCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnColorCode((String) value);
            }
        }
        ,
        VpnColorName {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getVpnColorName();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setVpnColorName((String) value);
            }
        }
        ,
        CommodityId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getCommodityId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setCommodityId((BigDecimal) value);
            }
        }
        ,
        CommodityCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getCommodityCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setCommodityCode((String) value);
            }
        }
        ,
        CommodityDesc {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getCommodityDesc();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setCommodityDesc((String) value);
            }
        }
        ,
        RegionId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getRegionId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setRegionId((BigDecimal) value);
            }
        }
        ,
        RegionCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getRegionCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setRegionCode((String) value);
            }
        }
        ,
        RegionDesc {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getRegionDesc();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setRegionDesc((String) value);
            }
        }
        ,
        StoreId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getStoreId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setStoreId((BigDecimal) value);
            }
        }
        ,
        StoreCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getStoreCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setStoreCode((String) value);
            }
        }
        ,
        StoreDesc {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getStoreDesc();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setStoreDesc((String) value);
            }
        }
        ,
        SupplierId {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSupplierId();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSupplierId((BigDecimal) value);
            }
        }
        ,
        SupplierCode {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSupplierCode();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSupplierCode((String) value);
            }
        }
        ,
        SuppDesc {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getSuppDesc();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setSuppDesc((String) value);
            }
        }
        ,
        OnSaleDate {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getOnSaleDate();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setOnSaleDate((Date) value);
            }
        }
        ,
        OnSupplyDate {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getOnSupplyDate();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setOnSupplyDate((Date) value);
            }
        }
        ,
        OffSaleDate {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getOffSaleDate();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setOffSaleDate((Date) value);
            }
        }
        ,
        OffSupplyDate {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getOffSupplyDate();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setOffSupplyDate((Date) value);
            }
        }
        ,
        Flag {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getFlag();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setFlag((Integer) value);
            }
        }
        ,
        Check1 {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getCheck1();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setCheck1((Boolean) value);
            }
        }
        ,
        AllStores {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getAllStores();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setAllStores((String) value);
            }
        }
        ,
        AllItems {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getAllItems();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setAllItems((String) value);
            }
        }
        ,
        UpdateUser {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getUpdateUser();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setUpdateUser((String) value);
            }
        }
        ,
        UpdateDate {
            public Object get(OnOffSaleSupplyResultsEOImpl obj) {
                return obj.getUpdateDate();
            }

            public void put(OnOffSaleSupplyResultsEOImpl obj, Object value) {
                obj.setUpdateDate((Date) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(OnOffSaleSupplyResultsEOImpl object);

        public abstract void put(OnOffSaleSupplyResultsEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int DEPTID = AttributesEnum.DeptId.index();
    public static final int DEPTCODE = AttributesEnum.DeptCode.index();
    public static final int DEPTNAME = AttributesEnum.DeptName.index();
    public static final int CLASSID = AttributesEnum.ClassId.index();
    public static final int CLASSCODE = AttributesEnum.ClassCode.index();
    public static final int CLASSNAME = AttributesEnum.ClassName.index();
    public static final int SUBCLASSID = AttributesEnum.SubclassId.index();
    public static final int SUBCLASSCODE = AttributesEnum.SubclassCode.index();
    public static final int SUBCLASSNAME = AttributesEnum.SubclassName.index();
    public static final int VPNID = AttributesEnum.VpnId.index();
    public static final int VPNCODE = AttributesEnum.VpnCode.index();
    public static final int VPNDESC = AttributesEnum.VpnDesc.index();
    public static final int VPNCOLORID = AttributesEnum.VpnColorId.index();
    public static final int VPNCOLORCODE = AttributesEnum.VpnColorCode.index();
    public static final int VPNCOLORNAME = AttributesEnum.VpnColorName.index();
    public static final int COMMODITYID = AttributesEnum.CommodityId.index();
    public static final int COMMODITYCODE = AttributesEnum.CommodityCode.index();
    public static final int COMMODITYDESC = AttributesEnum.CommodityDesc.index();
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int REGIONDESC = AttributesEnum.RegionDesc.index();
    public static final int STOREID = AttributesEnum.StoreId.index();
    public static final int STORECODE = AttributesEnum.StoreCode.index();
    public static final int STOREDESC = AttributesEnum.StoreDesc.index();
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int SUPPLIERCODE = AttributesEnum.SupplierCode.index();
    public static final int SUPPDESC = AttributesEnum.SuppDesc.index();
    public static final int ONSALEDATE = AttributesEnum.OnSaleDate.index();
    public static final int ONSUPPLYDATE = AttributesEnum.OnSupplyDate.index();
    public static final int OFFSALEDATE = AttributesEnum.OffSaleDate.index();
    public static final int OFFSUPPLYDATE = AttributesEnum.OffSupplyDate.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int CHECK1 = AttributesEnum.Check1.index();
    public static final int ALLSTORES = AttributesEnum.AllStores.index();
    public static final int ALLITEMS = AttributesEnum.AllItems.index();
    public static final int UPDATEUSER = AttributesEnum.UpdateUser.index();
    public static final int UPDATEDATE = AttributesEnum.UpdateDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OnOffSaleSupplyResultsEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.retail.apps.aipdt.osos.model.entity.OnOffSaleSupplyResultsEO");
    }


    /**
     * Gets the attribute value for DeptName, using the alias name DeptName.
     * @return the value of DeptName
     */
    public String getDeptName() {
        return (String) getAttributeInternal(DEPTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptName.
     * @param value value to set the DeptName
     */
    public void setDeptName(String value) {
        setAttributeInternal(DEPTNAME, value);
    }


    /**
     * Gets the attribute value for ClassName, using the alias name ClassName.
     * @return the value of ClassName
     */
    public String getClassName() {
        return (String) getAttributeInternal(CLASSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClassName.
     * @param value value to set the ClassName
     */
    public void setClassName(String value) {
        setAttributeInternal(CLASSNAME, value);
    }


    /**
     * Gets the attribute value for SubclassName, using the alias name SubclassName.
     * @return the value of SubclassName
     */
    public String getSubclassName() {
        return (String) getAttributeInternal(SUBCLASSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubclassName.
     * @param value value to set the SubclassName
     */
    public void setSubclassName(String value) {
        setAttributeInternal(SUBCLASSNAME, value);
    }


    /**
     * Gets the attribute value for VpnDesc, using the alias name VpnDesc.
     * @return the value of VpnDesc
     */
    public String getVpnDesc() {
        return (String) getAttributeInternal(VPNDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnDesc.
     * @param value value to set the VpnDesc
     */
    public void setVpnDesc(String value) {
        setAttributeInternal(VPNDESC, value);
    }


    /**
     * Gets the attribute value for StoreDesc, using the alias name StoreDesc.
     * @return the value of StoreDesc
     */
    public String getStoreDesc() {
        return (String) getAttributeInternal(STOREDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StoreDesc.
     * @param value value to set the StoreDesc
     */
    public void setStoreDesc(String value) {
        setAttributeInternal(STOREDESC, value);
    }


    /**
     * Gets the attribute value for SuppDesc, using the alias name SuppDesc.
     * @return the value of SuppDesc
     */
    public String getSuppDesc() {
        return (String) getAttributeInternal(SUPPDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SuppDesc.
     * @param value value to set the SuppDesc
     */
    public void setSuppDesc(String value) {
        setAttributeInternal(SUPPDESC, value);
    }

    /**
     * Gets the attribute value for OnSaleDate, using the alias name OnSaleDate.
     * @return the value of OnSaleDate
     */
    public Date getOnSaleDate() {
        return (Date) getAttributeInternal(ONSALEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnSaleDate.
     * @param value value to set the OnSaleDate
     */
    public void setOnSaleDate(Date value) {
        setAttributeInternal(ONSALEDATE, value);
    }

    /**
     * Gets the attribute value for OnSupplyDate, using the alias name OnSupplyDate.
     * @return the value of OnSupplyDate
     */
    public Date getOnSupplyDate() {
        return (Date) getAttributeInternal(ONSUPPLYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OnSupplyDate.
     * @param value value to set the OnSupplyDate
     */
    public void setOnSupplyDate(Date value) {
        setAttributeInternal(ONSUPPLYDATE, value);
    }

    /**
     * Gets the attribute value for OffSaleDate, using the alias name OffSaleDate.
     * @return the value of OffSaleDate
     */
    public Date getOffSaleDate() {
        return (Date) getAttributeInternal(OFFSALEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OffSaleDate.
     * @param value value to set the OffSaleDate
     */
    public void setOffSaleDate(Date value) {
        setAttributeInternal(OFFSALEDATE, value);
    }

    /**
     * Gets the attribute value for OffSupplyDate, using the alias name OffSupplyDate.
     * @return the value of OffSupplyDate
     */
    public Date getOffSupplyDate() {
        return (Date) getAttributeInternal(OFFSUPPLYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OffSupplyDate.
     * @param value value to set the OffSupplyDate
     */
    public void setOffSupplyDate(Date value) {
        setAttributeInternal(OFFSUPPLYDATE, value);
    }

    /**
     * Gets the attribute value for Flag, using the alias name Flag.
     * @return the value of Flag
     */
    public Integer getFlag() {
        return (Integer) getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flag.
     * @param value value to set the Flag
     */
    public void setFlag(Integer value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for Check1, using the alias name Check1.
     * @return the value of Check1
     */
    public Boolean getCheck1() {
        return (Boolean) getAttributeInternal(CHECK1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Check1.
     * @param value value to set the Check1
     */
    public void setCheck1(Boolean value) {
        setAttributeInternal(CHECK1, value);
    }


    /**
     * Gets the attribute value for StoreId, using the alias name StoreId.
     * @return the value of StoreId
     */
    public BigDecimal getStoreId() {
        return (BigDecimal) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StoreId.
     * @param value value to set the StoreId
     */
    public void setStoreId(BigDecimal value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for SupplierId, using the alias name SupplierId.
     * @return the value of SupplierId
     */
    public BigDecimal getSupplierId() {
        return (BigDecimal) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierId.
     * @param value value to set the SupplierId
     */
    public void setSupplierId(BigDecimal value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for RegionDesc, using the alias name RegionDesc.
     * @return the value of RegionDesc
     */
    public String getRegionDesc() {
        return (String) getAttributeInternal(REGIONDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegionDesc.
     * @param value value to set the RegionDesc
     */
    public void setRegionDesc(String value) {
        setAttributeInternal(REGIONDESC, value);
    }

    /**
     * Gets the attribute value for RegionCode, using the alias name RegionCode.
     * @return the value of RegionCode
     */
    public String getRegionCode() {
        return (String) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegionCode.
     * @param value value to set the RegionCode
     */
    public void setRegionCode(String value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for RegionId, using the alias name RegionId.
     * @return the value of RegionId
     */
    public BigDecimal getRegionId() {
        return (BigDecimal) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RegionId.
     * @param value value to set the RegionId
     */
    public void setRegionId(BigDecimal value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for AllStores, using the alias name AllStores.
     * @return the value of AllStores
     */
    public String getAllStores() {
        return (String) getAttributeInternal(ALLSTORES);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllStores.
     * @param value value to set the AllStores
     */
    public void setAllStores(String value) {
        setAttributeInternal(ALLSTORES, value);
    }

    /**
     * Gets the attribute value for AllItems, using the alias name AllItems.
     * @return the value of AllItems
     */
    public String getAllItems() {
        return (String) getAttributeInternal(ALLITEMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllItems.
     * @param value value to set the AllItems
     */
    public void setAllItems(String value) {
        setAttributeInternal(ALLITEMS, value);
    }

    /**
     * Gets the attribute value for DeptId, using the alias name DeptId.
     * @return the value of DeptId
     */
    public BigDecimal getDeptId() {
        return (BigDecimal) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptId.
     * @param value value to set the DeptId
     */
    public void setDeptId(BigDecimal value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for ClassId, using the alias name ClassId.
     * @return the value of ClassId
     */
    public BigDecimal getClassId() {
        return (BigDecimal) getAttributeInternal(CLASSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClassId.
     * @param value value to set the ClassId
     */
    public void setClassId(BigDecimal value) {
        setAttributeInternal(CLASSID, value);
    }

    /**
     * Gets the attribute value for SubclassId, using the alias name SubclassId.
     * @return the value of SubclassId
     */
    public BigDecimal getSubclassId() {
        return (BigDecimal) getAttributeInternal(SUBCLASSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubclassId.
     * @param value value to set the SubclassId
     */
    public void setSubclassId(BigDecimal value) {
        setAttributeInternal(SUBCLASSID, value);
    }

    /**
     * Gets the attribute value for VpnId, using the alias name VpnId.
     * @return the value of VpnId
     */
    public BigDecimal getVpnId() {
        return (BigDecimal) getAttributeInternal(VPNID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnId.
     * @param value value to set the VpnId
     */
    public void setVpnId(BigDecimal value) {
        setAttributeInternal(VPNID, value);
    }


    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for DeptCode, using the alias name DeptCode.
     * @return the value of DeptCode
     */
    public String getDeptCode() {
        return (String) getAttributeInternal(DEPTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptCode.
     * @param value value to set the DeptCode
     */
    public void setDeptCode(String value) {
        setAttributeInternal(DEPTCODE, value);
    }

    /**
     * Gets the attribute value for ClassCode, using the alias name ClassCode.
     * @return the value of ClassCode
     */
    public String getClassCode() {
        return (String) getAttributeInternal(CLASSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClassCode.
     * @param value value to set the ClassCode
     */
    public void setClassCode(String value) {
        setAttributeInternal(CLASSCODE, value);
    }

    /**
     * Gets the attribute value for SubclassCode, using the alias name SubclassCode.
     * @return the value of SubclassCode
     */
    public String getSubclassCode() {
        return (String) getAttributeInternal(SUBCLASSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubclassCode.
     * @param value value to set the SubclassCode
     */
    public void setSubclassCode(String value) {
        setAttributeInternal(SUBCLASSCODE, value);
    }

    /**
     * Gets the attribute value for VpnCode, using the alias name VpnCode.
     * @return the value of VpnCode
     */
    public String getVpnCode() {
        return (String) getAttributeInternal(VPNCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnCode.
     * @param value value to set the VpnCode
     */
    public void setVpnCode(String value) {
        setAttributeInternal(VPNCODE, value);
    }

    /**
     * Gets the attribute value for VpnColorId, using the alias name VpnColorId.
     * @return the value of VpnColorId
     */
    public BigDecimal getVpnColorId() {
        return (BigDecimal) getAttributeInternal(VPNCOLORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnColorId.
     * @param value value to set the VpnColorId
     */
    public void setVpnColorId(BigDecimal value) {
        setAttributeInternal(VPNCOLORID, value);
    }

    /**
     * Gets the attribute value for VpnColorCode, using the alias name VpnColorCode.
     * @return the value of VpnColorCode
     */
    public String getVpnColorCode() {
        return (String) getAttributeInternal(VPNCOLORCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnColorCode.
     * @param value value to set the VpnColorCode
     */
    public void setVpnColorCode(String value) {
        setAttributeInternal(VPNCOLORCODE, value);
    }

    /**
     * Gets the attribute value for VpnColorName, using the alias name VpnColorName.
     * @return the value of VpnColorName
     */
    public String getVpnColorName() {
        return (String) getAttributeInternal(VPNCOLORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for VpnColorName.
     * @param value value to set the VpnColorName
     */
    public void setVpnColorName(String value) {
        setAttributeInternal(VPNCOLORNAME, value);
    }

    /**
     * Gets the attribute value for CommodityId, using the alias name CommodityId.
     * @return the value of CommodityId
     */
    public BigDecimal getCommodityId() {
        return (BigDecimal) getAttributeInternal(COMMODITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommodityId.
     * @param value value to set the CommodityId
     */
    public void setCommodityId(BigDecimal value) {
        setAttributeInternal(COMMODITYID, value);
    }

    /**
     * Gets the attribute value for CommodityCode, using the alias name CommodityCode.
     * @return the value of CommodityCode
     */
    public String getCommodityCode() {
        return (String) getAttributeInternal(COMMODITYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommodityCode.
     * @param value value to set the CommodityCode
     */
    public void setCommodityCode(String value) {
        setAttributeInternal(COMMODITYCODE, value);
    }

    /**
     * Gets the attribute value for CommodityDesc, using the alias name CommodityDesc.
     * @return the value of CommodityDesc
     */
    public String getCommodityDesc() {
        return (String) getAttributeInternal(COMMODITYDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommodityDesc.
     * @param value value to set the CommodityDesc
     */
    public void setCommodityDesc(String value) {
        setAttributeInternal(COMMODITYDESC, value);
    }

    /**
     * Gets the attribute value for StoreCode, using the alias name StoreCode.
     * @return the value of StoreCode
     */
    public String getStoreCode() {
        return (String) getAttributeInternal(STORECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StoreCode.
     * @param value value to set the StoreCode
     */
    public void setStoreCode(String value) {
        setAttributeInternal(STORECODE, value);
    }

    /**
     * Gets the attribute value for SupplierCode, using the alias name SupplierCode.
     * @return the value of SupplierCode
     */
    public String getSupplierCode() {
        return (String) getAttributeInternal(SUPPLIERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierCode.
     * @param value value to set the SupplierCode
     */
    public void setSupplierCode(String value) {
        setAttributeInternal(SUPPLIERCODE, value);
    }

    /**
     * Gets the attribute value for UpdateUser, using the alias name UpdateUser.
     * @return the value of UpdateUser
     */
    public String getUpdateUser() {
        return (String) getAttributeInternal(UPDATEUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdateUser.
     * @param value value to set the UpdateUser
     */
    public void setUpdateUser(String value) {
        setAttributeInternal(UPDATEUSER, value);
    }

    /**
     * Gets the attribute value for UpdateDate, using the alias name UpdateDate.
     * @return the value of UpdateDate
     */
    public Date getUpdateDate() {
        return (Date) getAttributeInternal(UPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdateDate.
     * @param value value to set the UpdateDate
     */
    public void setUpdateDate(Date value) {
        setAttributeInternal(UPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }

    /**
     * Validation method for OnOffSaleSupplyResultsEO.
     */
    public boolean validateOnOffSaleSupplyResultsEO() {
        return true;
    }


    /**
     * Validation method for OnOffSaleSupplyResultsEO.
     */
    public boolean validateOnSaleandSupplyDate() {
        return true;
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

