package oracle.retail.apps.aipdt.cds.model.view;

import java.math.BigDecimal;

import oracle.retail.apps.aipdt.common.adfbc.AipdtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 24 15:10:06 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrossDockSetupRowDOWVOImpl extends AipdtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CrossDockSetupRowDOWVOImpl() {
    }

    /**
     * Returns the bind variable value for bindId.
     * @return bind variable value for bindId
     */
    public BigDecimal getbindId() {
        return (BigDecimal) getNamedWhereClauseParam("bindId");
    }

    /**
     * Sets <code>value</code> for bind variable bindId.
     * @param value value to bind as bindId
     */
    public void setbindId(BigDecimal value) {
        setNamedWhereClauseParam("bindId", value);
    }
}

